# Generated by Django 5.2.5 on 2025-10-11 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_article_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="articles.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["article"], name="articles_ar_article_e9de36_idx"
                    ),
                    models.Index(
                        fields=["user"], name="articles_ar_user_id_3a5f1f_idx"
                    ),
                    models.Index(
                        fields=["session_key"], name="articles_ar_session_5834a3_idx"
                    ),
                    models.Index(
                        fields=["ip_address", "created_at"],
                        name="articles_ar_ip_addr_7b4af7_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("article", "user"),
                        name="unique_user_like",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("session_key__isnull", False)),
                        fields=("article", "session_key"),
                        name="unique_session_like",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ArticleShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("twitter", "Twitter"),
                            ("facebook", "Facebook"),
                            ("linkedin", "LinkedIn"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("email", "Email"),
                            ("copy_link", "Copy Link"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("shared_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="articles.article",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["article", "platform"],
                        name="articles_ar_article_ec44a6_idx",
                    ),
                    models.Index(
                        fields=["shared_at"], name="articles_ar_shared__02e478_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Maximum 1000 characters", max_length=1000
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_edited", models.BooleanField(default=False)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="articles.article",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["article", "created_at"],
                        name="articles_co_article_1d93b8_idx",
                    ),
                    models.Index(
                        fields=["author"], name="articles_co_author__3b3778_idx"
                    ),
                ],
            },
        ),
    ]
