#!/usr/bin/env python
"""
Production data sync script for GameLearningModule
Run this in production Django shell: python manage.py shell < sync_gamelearningmodule_production.py
"""
import os
import django

# Setup Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'decipherworld.settings.production')
django.setup()

from group_learning.models import GameLearningModule, ConstitutionQuestion, ConstitutionOption

def sync_gamelearningmodule_data():
    """Sync GameLearningModule data to production"""
    
    print("=== SYNCING GameLearningModule DATA TO PRODUCTION ===")
    
    # Data to create
    modules_data = [
        {'title': 'Sample: Understanding Democracy', 'game_type': 'constitution_challenge', 'trigger_condition': 'topic_based', 'is_enabled': False, 'is_skippable': True, 'display_timing': 'instant', 'principle_explanation': 'Democracy is a system of government where power ultimately rests with the people. In a democratic system, citizens have the right to participate in decision-making processes, either directly or through elected representatives.\n\nThe word "democracy" comes from the Greek words "demos" (people) and "kratos" (power or rule), literally meaning "rule by the people." This fundamental principle ensures that government serves the interests of its citizens rather than a small elite group.', 'key_takeaways': '• Democracy means "rule by the people" - citizens have ultimate power\n• People participate through voting and electing representatives\n• Democratic governments are accountable to their citizens\n• Individual rights are protected even within majority rule\n• Democratic systems include checks and balances to prevent abuse of power', 'historical_context': 'The concept of democracy has ancient roots, with early examples in ancient Greece around 500 BCE. The city-state of Athens practiced direct democracy where citizens could directly participate in decision-making.\n\nModern democracy evolved through centuries of struggle, with key milestones including the Magna Carta (1215), the American Revolution (1776), and the French Revolution (1789). Each contributed ideas about limiting government power and protecting individual rights.', 'real_world_example': "India is the world's largest democracy, with over 900 million eligible voters. During elections, citizens from diverse backgrounds - farmers, urban professionals, students - all have equal voting power regardless of their economic status.\n\nThe Indian Constitution ensures that even minority voices are heard through reserved seats in Parliament and state legislatures. This shows how democracy can work in a diverse, multi-cultural society.", 'action_impact_title': 'Impact of Your Decision', 'constitution_topic_title': 'Learn from the Indian Constitution', 'trigger_topic': 'leadership'},
        {'title': 'Sample: Fundamental Rights', 'game_type': 'constitution_challenge', 'trigger_condition': 'topic_based', 'is_enabled': False, 'is_skippable': True, 'display_timing': 'instant', 'principle_explanation': 'Fundamental rights are basic human rights guaranteed by the Constitution that protect individual freedom and dignity. These rights create a protective shield around citizens, ensuring the government cannot arbitrarily restrict their liberties.\n\nThe Indian Constitution guarantees six fundamental rights: Right to Equality, Right to Freedom, Right against Exploitation, Right to Freedom of Religion, Cultural and Educational Rights, and Right to Constitutional Remedies. These rights are enforceable by courts and are essential for human dignity.', 'key_takeaways': '• Fundamental rights protect individual freedom and dignity\n• These rights are guaranteed by the Constitution and enforced by courts\n• They include equality, freedom, protection from exploitation, and religious freedom\n• Right to Constitutional Remedies allows citizens to approach courts when rights are violated\n• Rights come with responsibilities - freedom must be exercised responsibly', 'historical_context': "The concept of fundamental rights emerged from centuries of struggle against oppression. The American Bill of Rights (1791) and the French Declaration of Rights (1789) were early examples.\n\nIndia's freedom struggle highlighted the need for protecting individual rights. Leaders like Dr. B.R. Ambedkar, who chaired the Constitution Drafting Committee, ensured that fundamental rights would be an integral part of independent India's Constitution.", 'real_world_example': 'When the government tried to impose emergency in 1975, many fundamental rights were suspended. Citizens could be arrested without trial, and press freedom was curtailed. \n\nThis experience taught Indians the importance of protecting fundamental rights. After the emergency was lifted in 1977, constitutional amendments were made to ensure such violations could never happen again, showing how rights protect democracy itself.', 'action_impact_title': 'Impact of Your Decision', 'constitution_topic_title': 'Learn from the Indian Constitution', 'trigger_topic': 'rights'},
        {'title': 'Sample: Justice and Fairness', 'game_type': 'constitution_challenge', 'trigger_condition': 'topic_based', 'is_enabled': False, 'is_skippable': True, 'display_timing': 'instant', 'principle_explanation': 'Justice means treating all people fairly and equally under the law. A just system ensures that everyone gets what they deserve based on their actions and circumstances, not their background, wealth, or social status.\n\nThe Constitution establishes an independent judiciary to ensure justice. Courts interpret laws, settle disputes, and protect citizens\' rights. The principle "justice delayed is justice denied" emphasizes that fair treatment must be both accessible and timely.', 'key_takeaways': '• Justice means treating all people fairly and equally under the law\n• Independent judiciary protects citizens from government overreach\n• Courts interpret laws and settle disputes impartially\n• Everyone has the right to a fair trial and legal representation\n• Justice must be accessible to all, regardless of social or economic status', 'historical_context': 'The idea of impartial justice has deep roots in human civilization. Ancient codes like Hammurabi\'s Code (1750 BCE) established early legal principles.\n\nIn India, the concept of "Dharma" traditionally emphasized righteous conduct and fair treatment. The modern Indian judicial system combines this heritage with contemporary legal principles, creating a system that respects both tradition and progress.', 'real_world_example': "The Right to Information Act (2005) empowers ordinary citizens to seek information from government offices. A farmer in rural Maharashtra used RTI to discover corruption in a local development project.\n\nDespite having limited resources, the farmer could approach courts for justice. The case was decided purely on facts and law, not on the farmer's social status, demonstrating how justice works equally for all citizens.", 'action_impact_title': 'Impact of Your Decision', 'constitution_topic_title': 'Learn from the Indian Constitution', 'trigger_topic': 'justice'},
        {'title': 'Sample: Citizen Participation', 'game_type': 'constitution_challenge', 'trigger_condition': 'topic_based', 'is_enabled': False, 'is_skippable': True, 'display_timing': 'instant', 'principle_explanation': "Citizen participation is the cornerstone of democracy. It means that people don't just vote once every few years, but actively engage in the democratic process through various means - voting, contesting elections, participating in public debates, and holding government accountable.\n\nEffective citizen participation requires both rights and responsibilities. Citizens must stay informed about issues, participate constructively in debates, and exercise their civic duties responsibly. Democracy works best when citizens are engaged and active.", 'key_takeaways': '• Democracy requires active participation from citizens, not just voting\n• Citizens can participate through elections, public debates, and civic activities\n• Staying informed about issues is a civic responsibility\n• Peaceful protest and constructive criticism strengthen democracy\n• Local participation (panchayats, municipal bodies) is as important as national politics', 'historical_context': "The Indian independence movement was built on mass participation. Mahatma Gandhi's methods showed how ordinary citizens could participate in political change through non-violent resistance.\n\nThe 73rd and 74th Constitutional Amendments (1992) created local self-government institutions (panchayats and municipalities), bringing democracy closer to people and encouraging grassroots participation.", 'real_world_example': "In Kerala, the People's Planning Campaign involves citizens directly in planning local development projects. Villagers gather in gram sabhas (village assemblies) to discuss priorities like road construction, water supply, and education.\n\nThese meetings aren't just consultative - citizens make actual decisions about how government funds are spent in their area. This shows how meaningful participation goes beyond voting to include direct involvement in governance.", 'action_impact_title': 'Impact of Your Decision', 'constitution_topic_title': 'Learn from the Indian Constitution', 'trigger_topic': 'participation'},
        {'title': 'Sample: Checks and Balances', 'game_type': 'constitution_challenge', 'trigger_condition': 'topic_based', 'is_enabled': False, 'is_skippable': True, 'display_timing': 'instant', 'principle_explanation': 'Checks and balances prevent any single institution from becoming too powerful. In a democracy, power is distributed among different branches of government - legislative (makes laws), executive (implements laws), and judiciary (interprets laws) - so they can monitor and limit each other.\n\nThis system ensures that no person or group can abuse power. Each branch has specific powers but also faces limitations from the other branches. This balance protects democracy from both tyranny and chaos.', 'key_takeaways': '• Power is divided among legislature, executive, and judiciary to prevent abuse\n• Each branch can limit the others through constitutional mechanisms\n• Parliament can impeach judges, courts can strike down unconstitutional laws\n• President can return bills to Parliament for reconsideration\n• Independent institutions like Election Commission ensure fair governance', 'historical_context': 'The concept was developed by French philosopher Montesquieu and implemented in the American Constitution. The Indian Constitution adopted this principle while adapting it to parliamentary democracy.\n\nDr. B.R. Ambedkar emphasized that constitutional methods must be used to achieve social and political goals, highlighting the importance of institutional safeguards over individual personalities.', 'real_world_example': "In 2019, the Supreme Court held that the Chief Justice of India's office falls under the Right to Information Act. This decision, opposed by the executive, showed how judicial independence works.\n\nWhen Parliament passes a law, courts can review if it violates constitutional principles. When governments try to influence elections, the Election Commission can take action. These real-world checks prevent any single institution from dominating others.", 'action_impact_title': 'Impact of Your Decision', 'constitution_topic_title': 'Learn from the Indian Constitution', 'trigger_topic': 'checks'},
        {'title': 'Sample: Achieving High Governance Score', 'game_type': 'constitution_challenge', 'trigger_condition': 'score_based', 'is_enabled': False, 'is_skippable': True, 'display_timing': 'instant', 'principle_explanation': "Congratulations on building a strong democratic foundation! High governance scores indicate that your constitutional choices are creating a balanced, fair, and effective system of government.\n\nYour decisions show understanding of how different constitutional principles work together. Democracy isn't just about one aspect - it requires balancing majority rule with minority rights, efficiency with accountability, and individual freedom with collective responsibility.", 'key_takeaways': '• Strong democracy requires balance between competing values\n• High scores show good understanding of constitutional principles\n• Effective governance combines multiple elements working together\n• Your choices demonstrate civic maturity and democratic thinking\n• Real democracy is an ongoing process of balancing different needs', 'action_impact_title': 'Impact of Your Decision', 'constitution_topic_title': 'Learn from the Indian Constitution', 'min_score': 18},
        {'title': 'Democratic Rights and Good Governance', 'game_type': 'constitution_challenge', 'trigger_condition': 'always', 'is_enabled': True, 'is_skippable': True, 'display_timing': 'instant', 'principle_explanation': 'Democratic governance requires balancing majority rule with minority rights while ensuring transparency and accountability.', 'key_takeaways': '• Democratic decisions should consider all citizens\n• Transparency builds public trust\n• Minority rights must be protected\n• Accountability prevents corruption', 'action_impact_title': 'How Your Choice Shapes Democracy', 'governance_impact': 'Your decision to prioritize transparent governance over quick decision-making strengthens democratic institutions. While it may slow immediate progress, it builds long-term trust between citizens and government, creating a foundation for sustainable development.', 'score_reasoning': 'Governance score increased by +15 points because transparency and citizen participation are fundamental to healthy democracy. Citizens feel more engaged when they understand government decisions, leading to higher cooperation and legitimacy.', 'country_state_changes': 'The city grows more steadily as citizens trust government planning. Population satisfaction increases, leading to more skilled workers moving to your nation. Economic growth may be slower initially but becomes more sustainable and inclusive.', 'societal_impact': 'Citizens develop stronger civic engagement and trust in institutions. Social cohesion improves as all groups feel their voices are heard. This creates a positive cycle where democracy reinforces itself through participation.', 'constitution_topic_title': 'Indian Constitution: Democratic Principles', 'constitution_chapter': 'features', 'constitution_principle': 'Democratic Governance and Right to Information', 'constitution_explanation': 'The Indian Constitution establishes a democratic republic where sovereignty lies with the people. Article 19(1)(a) guarantees freedom of speech and expression, while the Right to Information Act (2005) ensures government transparency. The Preamble declares India as a "Democratic Republic," meaning all power flows from the people.', 'constitution_article_reference': 'Article 19(1)(a): Freedom of Speech and Expression; Preamble: Democratic Republic; Directive Principles Article 39(b): Distribution of material resources', 'historical_constitutional_context': 'During the Constituent Assembly debates, Dr. B.R. Ambedkar emphasized that democracy is not just about majority rule but about constitutional morality. The framers were inspired by the American Bill of Rights but adapted it to Indian conditions, ensuring that democracy would protect all communities.'},
        {'title': 'Balancing Individual Rights and Social Harmony', 'game_type': 'constitution_challenge', 'trigger_condition': 'topic_based', 'is_enabled': True, 'is_skippable': True, 'display_timing': 'instant', 'principle_explanation': 'Constitutional democracies must balance individual freedoms with collective welfare and social harmony.', 'key_takeaways': '• Individual rights are not absolute\n• Reasonable restrictions protect society\n• Balance prevents both tyranny and chaos\n• Constitutional framework guides decisions', 'action_impact_title': 'Impact of Rights vs. Harmony Balance', 'governance_impact': 'Your choice to allow peaceful protest while setting clear boundaries shows constitutional wisdom. This demonstrates that rights come with responsibilities, building a culture where freedom and order coexist.', 'score_reasoning': 'Governance score increased by +12 points for showing constitutional maturity. Citizens see that their rights are protected but not at the expense of social stability, creating trust in the legal system.', 'country_state_changes': 'Economic activity continues during controlled protests, showing foreign investors that your nation has stable institutions. Cities remain functional while allowing democratic expression, attracting both businesses and civil society organizations.', 'societal_impact': 'Citizens learn that democracy is about responsible freedom. Minority groups feel protected while majority groups see that rights have reasonable limits. This builds a mature democratic culture.', 'constitution_topic_title': 'Indian Constitution: Fundamental Rights and Restrictions', 'constitution_chapter': 'rights_duties', 'constitution_principle': 'Fundamental Rights with Reasonable Restrictions', 'constitution_explanation': 'The Indian Constitution grants fundamental rights in Articles 12-35, but these rights are not absolute. Article 19(2) allows "reasonable restrictions" on free speech for sovereignty, public order, and morality. This balance reflects the Constitution\'s wisdom in protecting both individual liberty and collective welfare.', 'constitution_article_reference': 'Article 19(1): Six Fundamental Rights; Article 19(2): Reasonable Restrictions; Article 21: Right to Life and Personal Liberty', 'historical_constitutional_context': 'The Constituent Assembly debated whether rights should be absolute or qualified. Influenced by the Irish Constitution and practical governance needs, they chose "reasonable restrictions" - a uniquely Indian approach that balances Western liberalism with social responsibility.', 'trigger_topic': 'fundamental_rights'},
    ]
    
    synced_count = 0
    updated_count = 0
    
    for module_data in modules_data:
        title = module_data['title']
        
        # Check if module already exists
        existing_module = GameLearningModule.objects.filter(title=title).first()
        
        if existing_module:
            # Update existing module
            for field, value in module_data.items():
                if field not in ['trigger_question_id', 'trigger_option_id']:
                    setattr(existing_module, field, value)
            
            # Handle foreign key fields
            if 'trigger_question_id' in module_data:
                try:
                    existing_module.trigger_question_id = module_data['trigger_question_id']
                except:
                    pass  # Ignore if question doesn't exist
            
            if 'trigger_option_id' in module_data:
                try:
                    existing_module.trigger_option_id = module_data['trigger_option_id']
                except:
                    pass  # Ignore if option doesn't exist
            
            existing_module.save()
            updated_count += 1
            print(f"✅ Updated: {title[:50]}...")
            
        else:
            # Create new module
            try:
                # Remove foreign key fields for initial creation
                create_data = {k: v for k, v in module_data.items() 
                              if k not in ['trigger_question_id', 'trigger_option_id']}
                
                new_module = GameLearningModule.objects.create(**create_data)
                
                # Set foreign key fields if they exist
                if 'trigger_question_id' in module_data:
                    try:
                        new_module.trigger_question_id = module_data['trigger_question_id']
                        new_module.save()
                    except:
                        pass
                
                if 'trigger_option_id' in module_data:
                    try:
                        new_module.trigger_option_id = module_data['trigger_option_id']
                        new_module.save()
                    except:
                        pass
                
                synced_count += 1
                print(f"✅ Created: {title[:50]}...")
                
            except Exception as e:
                print(f"❌ Failed to create {title[:30]}...: {e}")
    
    print(f"\n=== SYNC COMPLETE ===")
    print(f"Created: {synced_count} modules")
    print(f"Updated: {updated_count} modules")
    print(f"Total in production: {GameLearningModule.objects.count()}")

if __name__ == "__main__":
    sync_gamelearningmodule_data()
