# Generated by Django 5.2.5 on 2025-08-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolDemoRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(max_length=200, verbose_name="School Name"),
                ),
                (
                    "contact_person",
                    models.CharField(
                        max_length=100, verbose_name="Contact Person Name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Phone Number"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "student_count",
                    models.PositiveIntegerField(verbose_name="Number of Students"),
                ),
                (
                    "interested_products",
                    models.JSONField(
                        default=list,
                        help_text="Selected products the school is interested in",
                        verbose_name="Products of Interest",
                    ),
                ),
                (
                    "additional_requirements",
                    models.TextField(
                        blank=True,
                        help_text="Any specific requirements or questions",
                        verbose_name="Additional Requirements",
                    ),
                ),
                (
                    "preferred_demo_time",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Preferred Demo Time"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_contacted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "School Demo Request",
                "verbose_name_plural": "School Demo Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
