# Generated by Django 5.2.5 on 2025-09-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_schooldemorequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game_type",
                    models.CharField(
                        choices=[
                            ("password_fortress", "Password Fortress"),
                            ("cyberbully_crisis", "Cyberbully Crisis"),
                            ("robotic_buddy", "Robotic Buddy"),
                            ("animal_classification", "Animal Classification"),
                            ("emotion_recognition", "Emotion Recognition"),
                            ("group_learning", "Group Learning"),
                            ("constitution_basic", "Constitution Basic"),
                            ("constitution_advanced", "Constitution Advanced"),
                            ("financial_literacy", "Financial Literacy"),
                            ("entrepreneurship", "Entrepreneurship"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Game session identifier",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "player_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("player_age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1 Star - Not Good"),
                            (2, "2 Stars - Okay"),
                            (3, "3 Stars - Good"),
                            (4, "4 Stars - Great"),
                            (5, "5 Stars - Amazing"),
                        ],
                        help_text="Rating is mandatory",
                    ),
                ),
                (
                    "review_text",
                    models.TextField(
                        blank=True, help_text="Review text is optional", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Game Review",
                "verbose_name_plural": "Game Reviews",
                "ordering": ["-created_at"],
                "unique_together": {("game_type", "session_id")},
            },
        ),
    ]
