# Generated by Django 5.2.5 on 2025-09-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_mobile_number_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this course is actively offered"
            ),
        ),
    ]
