# Generated by Django 5.2.5 on 2025-10-14 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_course_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., School Events, Workshops)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of this category"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for display (lower numbers first)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this category is visible"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Photo Category",
                "verbose_name_plural": "Photo Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="VideoTestimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Testimonial title (e.g., 'Amazing AI Learning Experience')",
                        max_length=200,
                    ),
                ),
                (
                    "student_name",
                    models.CharField(
                        help_text="Name of the student giving testimonial",
                        max_length=100,
                    ),
                ),
                (
                    "student_grade",
                    models.CharField(
                        blank=True,
                        help_text="Student's grade/class (e.g., 'Grade 5', 'Class 10')",
                        max_length=50,
                    ),
                ),
                (
                    "school_name",
                    models.CharField(help_text="Name of the school", max_length=200),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload MP4 video file (recommended: under 50MB)",
                        upload_to="gallery/videos/",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Or paste YouTube/Vimeo URL instead of uploading file",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Custom thumbnail image (auto-generated if left blank)",
                        upload_to="gallery/video_thumbnails/",
                    ),
                ),
                (
                    "transcript",
                    models.TextField(
                        blank=True,
                        help_text="Full transcript of the video (for accessibility)",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Brief summary of what the student says"
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True,
                        help_text="Video duration (auto-detected when possible)",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for display (lower numbers first)"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show in featured testimonials section"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this testimonial is visible on the website",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Video Testimonial",
                "verbose_name_plural": "Video Testimonials",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PhotoGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Photo title or caption", max_length=200
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload high-quality image (recommended: 1200x800px or larger)",
                        upload_to="gallery/photos/",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Auto-generated thumbnail (leave blank)",
                        upload_to="gallery/thumbnails/",
                    ),
                ),
                (
                    "caption",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description or story behind the photo",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the school featured in this photo",
                        max_length=200,
                    ),
                ),
                (
                    "date_taken",
                    models.DateField(
                        blank=True, help_text="When was this photo taken?", null=True
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order for display within category (lower numbers first)",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show in featured photos section"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this photo is visible on the website",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Select the appropriate category",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.photocategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo Gallery Item",
                "verbose_name_plural": "Photo Gallery Items",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
