# Generated by Django 5.2.5 on 2025-10-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_gallery_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="videotestimonial",
            name="aspect_ratio",
            field=models.CharField(
                blank=True,
                help_text="Video aspect ratio (e.g., '16:9', '9:16' for portrait)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="videotestimonial",
            name="auto_thumbnail",
            field=models.URLField(
                blank=True, help_text="Auto-generated thumbnail URL (YouTube, etc.)"
            ),
        ),
        migrations.AddField(
            model_name="videotestimonial",
            name="video_height",
            field=models.PositiveIntegerField(
                blank=True, help_text="Video height in pixels", null=True
            ),
        ),
        migrations.AddField(
            model_name="videotestimonial",
            name="video_width",
            field=models.PositiveIntegerField(
                blank=True, help_text="Video width in pixels", null=True
            ),
        ),
    ]
