# Generated by Django 5.2.5 on 2025-11-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_add_video_enhancement_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolReferral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referrer_name",
                    models.CharField(max_length=100, verbose_name="Your Name"),
                ),
                (
                    "referrer_email",
                    models.EmailField(
                        max_length=254, verbose_name="Your Email Address"
                    ),
                ),
                (
                    "referrer_phone",
                    models.CharField(
                        help_text="Include country code (e.g., +91 9999999999)",
                        max_length=15,
                        verbose_name="Your Mobile Number",
                    ),
                ),
                (
                    "referrer_relationship",
                    models.CharField(
                        help_text="e.g., Parent, Teacher, Principal, Friend, etc.",
                        max_length=100,
                        verbose_name="Your Relationship to School",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(max_length=200, verbose_name="School Name"),
                ),
                ("school_address", models.TextField(verbose_name="School Address")),
                ("school_city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "school_state",
                    models.CharField(max_length=100, verbose_name="State"),
                ),
                (
                    "school_pincode",
                    models.CharField(max_length=10, verbose_name="Pincode"),
                ),
                (
                    "contact_person_name",
                    models.CharField(
                        max_length=100, verbose_name="School Contact Person Name"
                    ),
                ),
                (
                    "contact_person_designation",
                    models.CharField(
                        help_text="e.g., Principal, Vice Principal, Academic Coordinator",
                        max_length=100,
                        verbose_name="Designation",
                    ),
                ),
                (
                    "contact_person_email",
                    models.EmailField(
                        max_length=254, verbose_name="School Email Address"
                    ),
                ),
                (
                    "contact_person_phone",
                    models.CharField(
                        help_text="Include country code",
                        max_length=15,
                        verbose_name="School Phone Number",
                    ),
                ),
                (
                    "student_count",
                    models.PositiveIntegerField(
                        verbose_name="Total Number of Students"
                    ),
                ),
                (
                    "grade_levels",
                    models.CharField(
                        help_text="e.g., KG-8, 1-8, Pre-primary to 8th",
                        max_length=50,
                        verbose_name="Grades Offered",
                    ),
                ),
                (
                    "school_board",
                    models.CharField(
                        blank=True,
                        help_text="e.g., CBSE, ICSE, State Board, IB, etc.",
                        max_length=50,
                        verbose_name="School Board",
                    ),
                ),
                (
                    "current_education_programs",
                    models.TextField(
                        blank=True,
                        help_text="Any existing technology or educational programs in use",
                        verbose_name="Current Educational Programs/Systems",
                    ),
                ),
                (
                    "interest_level",
                    models.CharField(
                        choices=[
                            ("high", "High - Actively looking for solutions"),
                            ("medium", "Medium - Exploring options"),
                            ("low", "Low - Just curious"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="School's Interest Level",
                    ),
                ),
                (
                    "decision_timeline",
                    models.CharField(
                        choices=[
                            ("immediate", "Within 1 month"),
                            ("quarter", "Within 3 months"),
                            ("half_year", "Within 6 months"),
                            ("next_year", "Next academic year"),
                            ("not_sure", "Not sure"),
                        ],
                        default="not_sure",
                        max_length=30,
                        verbose_name="Expected Decision Timeline",
                    ),
                ),
                (
                    "additional_notes",
                    models.TextField(
                        blank=True,
                        help_text="Any other relevant details about the school or their requirements",
                        verbose_name="Additional Information",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("contacted", "School Contacted"),
                            ("qualified", "Qualified Referral"),
                            ("converted", "Converted - Payment Received"),
                            ("rejected", "Not Qualified"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Referral Status",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for tracking progress",
                        verbose_name="Admin Notes",
                    ),
                ),
                (
                    "reward_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=50000.0,
                        max_digits=10,
                        verbose_name="Reward Amount (₹)",
                    ),
                ),
                (
                    "reward_paid",
                    models.BooleanField(default=False, verbose_name="Reward Paid"),
                ),
                (
                    "reward_paid_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reward Payment Date"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contacted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "School Referral",
                "verbose_name_plural": "School Referrals",
                "ordering": ["-created_at"],
            },
        ),
    ]
