# Generated by Django 5.2.5 on 2025-11-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_schoolreferral"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schoolreferral",
            name="decision_timeline",
        ),
        migrations.RemoveField(
            model_name="schoolreferral",
            name="grade_levels",
        ),
        migrations.RemoveField(
            model_name="schoolreferral",
            name="student_count",
        ),
        migrations.AlterField(
            model_name="schoolreferral",
            name="school_board",
            field=models.CharField(
                choices=[
                    ("cbse", "CBSE"),
                    ("icse", "ICSE"),
                    ("state_board", "State Board"),
                    ("ib", "International Baccalaureate (IB)"),
                    ("cambridge", "Cambridge International"),
                    ("montessori", "Montessori"),
                    ("waldorf", "Waldorf/Steiner"),
                    ("others", "Others"),
                ],
                default="cbse",
                max_length=50,
                verbose_name="School Board/Curriculum",
            ),
        ),
    ]
