# Generated by Django 5.2.5 on 2025-11-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_referral_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_code",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="UDISE School Code",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="School Name"
                    ),
                ),
                ("state", models.CharField(db_index=True, max_length=100)),
                ("state_code", models.CharField(db_index=True, max_length=10)),
                ("district", models.CharField(db_index=True, max_length=100)),
                ("district_code", models.CharField(max_length=10)),
                ("sub_district", models.CharField(blank=True, max_length=100)),
                ("sub_district_code", models.CharField(blank=True, max_length=10)),
                ("cluster", models.CharField(blank=True, max_length=100)),
                ("village", models.CharField(blank=True, max_length=100)),
                ("udise_village_code", models.CharField(blank=True, max_length=20)),
                ("pincode", models.CharField(db_index=True, max_length=10)),
                ("ward", models.CharField(blank=True, max_length=50)),
                (
                    "school_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("primary", "Primary School"),
                            ("upper_primary", "Upper Primary School"),
                            ("secondary", "Secondary School"),
                            ("higher_secondary", "Higher Secondary School"),
                            ("pre_primary", "Pre Primary School"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "school_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("boys", "Boys"),
                            ("girls", "Girls"),
                            ("co_ed", "Co-Educational"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "management",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("government", "Government"),
                            ("private", "Private Unaided"),
                            ("aided", "Government Aided"),
                            ("central_govt", "Central Government"),
                            ("others", "Others"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "year_of_establishment",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("functional", "Functional"),
                            ("closed", "Closed"),
                            ("merged", "Merged"),
                            ("upgraded", "Upgraded"),
                        ],
                        db_index=True,
                        default="functional",
                        max_length=20,
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        blank=True,
                        choices=[("rural", "Rural"), ("urban", "Urban")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("class_from", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("class_to", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "affiliation_board_secondary",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "affiliation_board_higher_secondary",
                    models.CharField(blank=True, max_length=100),
                ),
                ("pre_primary_rooms", models.PositiveSmallIntegerField(default=0)),
                ("class_rooms", models.PositiveSmallIntegerField(default=0)),
                ("other_rooms", models.PositiveSmallIntegerField(default=0)),
                ("teachers", models.PositiveSmallIntegerField(default=0)),
                ("pre_primary_students", models.PositiveIntegerField(default=0)),
                ("students_class_1", models.PositiveIntegerField(default=0)),
                ("students_class_2", models.PositiveIntegerField(default=0)),
                ("students_class_3", models.PositiveIntegerField(default=0)),
                ("students_class_4", models.PositiveIntegerField(default=0)),
                ("students_class_5", models.PositiveIntegerField(default=0)),
                ("students_class_6", models.PositiveIntegerField(default=0)),
                ("students_class_7", models.PositiveIntegerField(default=0)),
                ("students_class_8", models.PositiveIntegerField(default=0)),
                ("students_class_9", models.PositiveIntegerField(default=0)),
                ("students_class_10", models.PositiveIntegerField(default=0)),
                ("students_class_11", models.PositiveIntegerField(default=0)),
                ("students_class_12", models.PositiveIntegerField(default=0)),
                ("non_primary_students", models.PositiveIntegerField(default=0)),
                (
                    "total_students",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "search_vector",
                    models.TextField(
                        blank=True,
                        help_text="Computed field for full-text search optimization",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "School",
                "verbose_name_plural": "Schools",
                "ordering": ["state", "district", "school_name"],
                "indexes": [
                    models.Index(
                        fields=["state", "district", "school_name"],
                        name="core_school_state_2c46f1_idx",
                    ),
                    models.Index(
                        fields=["pincode", "school_name"],
                        name="core_school_pincode_5171df_idx",
                    ),
                    models.Index(
                        fields=["management", "school_category", "status"],
                        name="core_school_managem_f0124a_idx",
                    ),
                    models.Index(
                        fields=["state_code", "district_code"],
                        name="core_school_state_c_783f10_idx",
                    ),
                    models.Index(
                        fields=["total_students", "status"],
                        name="core_school_total_s_f89603_idx",
                    ),
                    models.Index(
                        fields=["search_vector"], name="core_school_search__cc2f51_idx"
                    ),
                ],
            },
        ),
    ]
