# Generated by Django 5.2.5 on 2025-09-17 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyber_city", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CyberbullyChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("challenge_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=100)),
                ("background_story", models.TextField()),
                ("option_a", models.CharField(max_length=300)),
                (
                    "option_a_type",
                    models.CharField(
                        choices=[("friendly", "Friendly"), ("bully", "Bully")],
                        max_length=20,
                    ),
                ),
                ("option_b", models.CharField(max_length=300)),
                (
                    "option_b_type",
                    models.CharField(
                        choices=[("friendly", "Friendly"), ("bully", "Bully")],
                        max_length=20,
                    ),
                ),
                ("option_c", models.CharField(max_length=300)),
                (
                    "option_c_type",
                    models.CharField(
                        choices=[("friendly", "Friendly"), ("bully", "Bully")],
                        max_length=20,
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C")], max_length=1
                    ),
                ),
                ("explanation", models.TextField()),
                ("mentor_tip", models.TextField()),
                ("mentor_voice_text", models.TextField()),
            ],
            options={
                "db_table": "cyber_city_cyberbully_challenge",
                "ordering": ["challenge_number"],
            },
        ),
        migrations.AddField(
            model_name="cybercityplayer",
            name="cyberbully_challenges_completed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cybercityplayer",
            name="cyberbully_current_challenge",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="cybercityplayer",
            name="missions_completed",
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name="PlayerCyberbullyChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_given",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C")], max_length=1
                    ),
                ),
                ("is_correct", models.BooleanField()),
                ("points_earned", models.PositiveIntegerField(default=0)),
                (
                    "time_taken",
                    models.PositiveIntegerField(help_text="Seconds taken to answer"),
                ),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cyber_city.cyberbullychallenge",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cyberbully_responses",
                        to="cyber_city.cybercityplayer",
                    ),
                ),
            ],
            options={
                "db_table": "cyber_city_player_cyberbully_challenge",
                "indexes": [
                    models.Index(
                        fields=["player", "answered_at"],
                        name="cyber_city__player__4765fb_idx",
                    ),
                    models.Index(
                        fields=["challenge", "is_correct"],
                        name="cyber_city__challen_0c37e1_idx",
                    ),
                ],
                "unique_together": {("player", "challenge")},
            },
        ),
    ]
