# Generated by Django 5.2.8 on 2025-11-10 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Quest",
                "verbose_name_plural": "Quests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quest_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="quest_ciq.quest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
                "ordering": ["-joined_at"],
                "unique_together": {("user", "quest")},
            },
        ),
        migrations.CreateModel(
            name="QuestLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=100)),
                ("short_help", models.TextField(blank=True)),
                (
                    "schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON schema describing expected fields for this level",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="quest_ciq.quest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quest Level",
                "verbose_name_plural": "Quest Levels",
                "ordering": ["quest", "order"],
                "unique_together": {("quest", "order")},
            },
        ),
        migrations.CreateModel(
            name="QuestSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_frozen",
                    models.BooleanField(
                        default=False,
                        help_text="If true, user cannot submit new responses",
                    ),
                ),
                ("total_score", models.IntegerField(default=0)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="quest_ciq.participant",
                    ),
                ),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="quest_ciq.quest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quest Session",
                "verbose_name_plural": "Quest Sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveIntegerField(default=0)),
                ("total_score", models.IntegerField(default=0)),
                ("levels_completed", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to="quest_ciq.participant",
                    ),
                ),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to="quest_ciq.quest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leaderboard Entry",
                "verbose_name_plural": "Leaderboard Entries",
                "ordering": ["quest", "rank"],
                "unique_together": {("quest", "participant")},
            },
        ),
        migrations.CreateModel(
            name="LevelResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answers",
                    models.JSONField(
                        default=dict,
                        help_text="JSON field storing form responses for this level",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "prototype_upload",
                    models.ImageField(
                        blank=True,
                        help_text="Optional prototype image upload (max 2MB)",
                        null=True,
                        upload_to="quest_prototypes/",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="quest_ciq.questlevel",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="quest_ciq.questsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Level Response",
                "verbose_name_plural": "Level Responses",
                "ordering": ["session", "level__order"],
                "unique_together": {("session", "level")},
            },
        ),
    ]
