# Generated by Django 5.2.8 on 2025-11-10 19:16

import django.core.validators
import django.db.models.deletion
import quest_ciq.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CIQSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enable_ciq",
                    models.BooleanField(
                        default=True,
                        help_text="Enable Classroom Innovation Quest feature",
                    ),
                ),
                (
                    "max_file_size_mb",
                    models.IntegerField(
                        default=2, help_text="Maximum file upload size in MB"
                    ),
                ),
                (
                    "show_leaderboard",
                    models.BooleanField(
                        default=True, help_text="Show public leaderboard"
                    ),
                ),
            ],
            options={
                "verbose_name": "CIQ Settings",
                "verbose_name_plural": "CIQ Settings",
            },
        ),
        migrations.CreateModel(
            name="QuestLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="Level order (1=Empathy, 2=Define, 3=Ideate, 4=Prototype, 5=Test)",
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "description",
                    models.TextField(help_text="Instructions for students"),
                ),
                ("tooltip", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuestSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_code",
                    models.CharField(
                        default=quest_ciq.models.generate_session_code,
                        help_text="Unique code students use to join",
                        max_length=6,
                        unique=True,
                    ),
                ),
                (
                    "student_name",
                    models.CharField(help_text="Student's name", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "current_level",
                    models.IntegerField(
                        default=1,
                        help_text="Current level (1-5)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("total_score", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session_code"], name="quest_ciq_q_session_362dd0_idx"
                    ),
                    models.Index(
                        fields=["-total_score"], name="quest_ciq_q_total_s_2d75af_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PeerFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("peer_name", models.CharField(max_length=100)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_feedbacks",
                        to="quest_ciq.questsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LevelResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level_order",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "answers",
                    models.JSONField(
                        default=dict,
                        help_text="JSON structure of answers (varies by level)",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="quest_ciq.questsession",
                    ),
                ),
            ],
            options={
                "ordering": ["level_order"],
                "indexes": [
                    models.Index(
                        fields=["session", "level_order"],
                        name="quest_ciq_l_session_6ee8b8_idx",
                    )
                ],
                "unique_together": {("session", "level_order")},
            },
        ),
    ]
