# Generated by Django 5.2.8 on 2025-11-10 19:36

import django.core.validators
import django.db.models.deletion
import quest_ciq.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quest_ciq", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Quest name", max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=200, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClassRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Classroom name (e.g., 'Grade 8A')", max_length=200
                    ),
                ),
                (
                    "class_code",
                    models.CharField(
                        default=quest_ciq.models.generate_class_code,
                        help_text="Unique code for this classroom",
                        max_length=8,
                        unique=True,
                    ),
                ),
                (
                    "teacher_key",
                    models.CharField(
                        blank=True,
                        help_text="Alternative key for teacher access (no auth required)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        help_text="Teacher (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ciq_classrooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quest",
                    models.ForeignKey(
                        help_text="Which quest this classroom is doing",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classrooms",
                        to="quest_ciq.quest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="questsession",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                help_text="Classroom this session belongs to (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="quest_ciq.classroom",
            ),
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Team name", max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly team identifier", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        help_text="Which classroom this team belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="quest_ciq.classroom",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TeacherTeamScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        help_text="Teacher score (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Optional teacher comment", null=True
                    ),
                ),
                ("graded_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_scores",
                        to="quest_ciq.classroom",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ciq_grades_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_scores",
                        to="quest_ciq.quest",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_scores",
                        to="quest_ciq.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-graded_at"],
            },
        ),
        migrations.AddField(
            model_name="questsession",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="Team this session belongs to (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="quest_ciq.team",
            ),
        ),
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(
                fields=["class_code"], name="quest_ciq_c_class_c_7031f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["classroom", "slug"], name="quest_ciq_t_classro_541ef8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("classroom", "slug")},
        ),
        migrations.AddIndex(
            model_name="teacherteamscore",
            index=models.Index(
                fields=["classroom", "quest"], name="quest_ciq_t_classro_4d7377_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacherteamscore",
            index=models.Index(fields=["team"], name="quest_ciq_t_team_id_a43d74_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="teacherteamscore",
            unique_together={("team", "classroom", "quest")},
        ),
    ]
