# Generated by Django 5.2.8 on 2025-11-10 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quest_ciq", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="participant",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="participant",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quest_participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
