# Generated by Django 5.2.5 on 2025-09-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_learning", "0003_constitution_challenge_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="countrystate",
            name="visual_elements",
            field=models.JSONField(
                default=dict,
                help_text="\n        Detailed visual state for animated city rendering:\n        {\n            'terrain': {'type': 'barren|green|fertile', 'features': ['river', 'hills']},\n            'buildings': {\n                'residential': [{'type': 'hut|house|apartment', 'position': [x,y], 'level': 1-3}],\n                'civic': [{'type': 'school|courthouse|parliament', 'position': [x,y], 'status': 'building|complete'}],\n                'commercial': [{'type': 'market|mall', 'position': [x,y]}]\n            },\n            'citizens': {\n                'population': 50,\n                'mood': 'happy|neutral|angry',\n                'activities': ['celebration', 'protest', 'work']\n            },\n            'weather': {'type': 'sunny|cloudy|rainy|stormy', 'effects': ['rainbow', 'lightning']},\n            'animations': ['fireworks', 'construction', 'parade'],\n            'sound_cues': ['cheers', 'construction_sound', 'celebration_music']\n        }\n        ",
            ),
        ),
    ]
