# Generated by Django 5.2.5 on 2025-09-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_learning", "0006_enhanced_learning_module"),
    ]

    operations = [
        # Add enhanced learning module fields
        migrations.AddField(
            model_name='gamelearningmodule',
            name='action_impact_title',
            field=models.CharField(default='Impact of Your Decision', help_text='Title for the action reasoning section', max_length=200),
        ),
        migrations.AddField(
            model_name='gamelearningmodule',
            name='governance_impact',
            field=models.TextField(blank=True, help_text="How this choice affects the country's governance and democratic institutions"),
        ),
        migrations.AddField(
            model_name='gamelearningmodule',
            name='score_reasoning',
            field=models.TextField(blank=True, help_text='Why the governance score increased/decreased with this choice'),
        ),
        migrations.AddField(
            model_name='gamelearningmodule',
            name='country_state_changes',
            field=models.TextField(blank=True, help_text='How this choice affects city growth, population, economic prosperity, etc.'),
        ),
        migrations.AddField(
            model_name='gamelearningmodule',
            name='societal_impact',
            field=models.TextField(blank=True, help_text='Impact on citizens, rights, freedoms, and social harmony'),
        ),
        migrations.AddField(
            model_name='gamelearningmodule',
            name='constitution_topic_title',
            field=models.CharField(default='Learn from the Indian Constitution', help_text='Title for the constitution teaching section', max_length=200),
        ),
        migrations.AddField(
            model_name='gamelearningmodule',
            name='constitution_chapter',
            field=models.CharField(blank=True, choices=[('introduction', 'Introduction to Constitutions'), ('making', 'Making of the Indian Constitution'), ('features', 'Key Features and Values'), ('government_branches', 'Branches of Government'), ('rights_duties', "Citizens' Rights and Duties"), ('inclusivity', 'Inclusivity and Pluralism'), ('living_document', 'Constitution as a Living Document')], help_text='Main constitutional topic this question relates to', max_length=100),
        ),
        migrations.AddField(
            model_name='gamelearningmodule',
            name='constitution_principle',
            field=models.TextField(blank=True, help_text="Core constitutional principle illustrated by this question (e.g., 'Separation of Powers', 'Fundamental Rights')"),
        ),
        migrations.AddField(
            model_name='gamelearningmodule',
            name='constitution_explanation',
            field=models.TextField(blank=True, help_text='Detailed explanation of how this constitutional principle works in India'),
        ),
        migrations.AddField(
            model_name='gamelearningmodule',
            name='constitution_article_reference',
            field=models.CharField(blank=True, help_text="Specific Indian Constitution articles related to this topic (e.g., 'Article 14-18: Right to Equality')", max_length=200),
        ),
        migrations.AddField(
            model_name='gamelearningmodule',
            name='historical_constitutional_context',
            field=models.TextField(blank=True, help_text='Historical context of how this principle was included in the Indian Constitution'),
        ),
    ]
