# Generated by Django 5.2.5 on 2025-09-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_learning", "0007_add_enhanced_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="constitutionoption",
            name="country_state_changes",
            field=models.TextField(
                blank=True,
                help_text="How this choice affects city growth, population, economic prosperity, etc.",
            ),
        ),
        migrations.AddField(
            model_name="constitutionoption",
            name="governance_impact",
            field=models.TextField(
                blank=True,
                help_text="How this specific choice affects the country's governance and democratic institutions",
            ),
        ),
        migrations.AddField(
            model_name="constitutionoption",
            name="score_reasoning",
            field=models.TextField(
                blank=True,
                help_text="Why this specific choice increases/decreases the governance score",
            ),
        ),
        migrations.AddField(
            model_name="constitutionoption",
            name="societal_impact",
            field=models.TextField(
                blank=True,
                help_text="Impact of this choice on citizens, rights, freedoms, and social harmony",
            ),
        ),
    ]
