# Generated by Django 5.2.5 on 2025-09-20 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_learning", "0009_add_climate_game_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="climateplayerresponse",
            name="climate_scenario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="group_learning.climatescenario",
            ),
        ),
        migrations.AlterField(
            model_name="climateplayerresponse",
            name="selected_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="group_learning.climateoption",
            ),
        ),
    ]
