# Generated by Django 5.2.5 on 2025-09-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "group_learning",
            "0010_alter_climateplayerresponse_climate_scenario_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="climategamesession",
            name="current_timer_end",
            field=models.DateTimeField(
                blank=True, help_text="When current timer expires", null=True
            ),
        ),
        migrations.AddField(
            model_name="climategamesession",
            name="question_timer_enabled",
            field=models.BooleanField(
                default=True, help_text="Enable timer for question phase"
            ),
        ),
        migrations.AddField(
            model_name="climategamesession",
            name="round_duration_minutes",
            field=models.IntegerField(
                default=5, help_text="Duration for each round in minutes"
            ),
        ),
    ]
