# Generated by Django 5.2.5 on 2025-09-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_learning", "0011_climategamesession_current_timer_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="climategamesession",
            name="round_duration_minutes",
            field=models.IntegerField(
                default=10, help_text="Duration for each round in minutes"
            ),
        ),
    ]
