# Generated by Django 5.2.5 on 2025-10-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_learning", "0014_add_performance_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamsubmission",
            name="file_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("image", "Image/Photo"),
                    ("audio", "Audio Recording"),
                    ("document", "Document"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
