# Generated by Django 5.2.5 on 2025-10-31 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_learning", "0016_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="designmission",
            name="max_submissions",
        ),
        migrations.RemoveField(
            model_name="designmission",
            name="requires_file_upload",
        ),
        migrations.RemoveField(
            model_name="designmission",
            name="requires_text_submission",
        ),
        migrations.RemoveField(
            model_name="designthinkinggame",
            name="auto_advance_missions",
        ),
        migrations.RemoveField(
            model_name="designthinkinggame",
            name="default_mission_duration",
        ),
        migrations.RemoveField(
            model_name="designthinkinggame",
            name="enable_mentor_prompts",
        ),
        migrations.RemoveField(
            model_name="designthinkinggame",
            name="mentor_prompt_frequency",
        ),
        migrations.RemoveField(
            model_name="designthinkinggame",
            name="require_all_teams_complete",
        ),
        migrations.AddField(
            model_name="designmission",
            name="allow_optional_upload",
            field=models.BooleanField(
                default=False,
                help_text="Allow optional file upload (simplified from required)",
            ),
        ),
        migrations.AddField(
            model_name="designmission",
            name="input_schema",
            field=models.JSONField(
                default=dict,
                help_text="Simplified input requirements for this mission (radio, dropdown, text)",
            ),
        ),
        migrations.AddField(
            model_name="designmission",
            name="requires_all_team_members",
            field=models.BooleanField(
                default=True,
                help_text="All team members must complete inputs (vs. just one per team)",
            ),
        ),
        migrations.AddField(
            model_name="designthinkinggame",
            name="auto_advance_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable automatic phase progression when teams complete inputs",
            ),
        ),
        migrations.AddField(
            model_name="designthinkinggame",
            name="completion_threshold_percentage",
            field=models.IntegerField(
                default=100,
                help_text="Percentage of team members required to complete phase (50-100%)",
            ),
        ),
        migrations.AddField(
            model_name="designthinkinggame",
            name="enable_teacher_scoring",
            field=models.BooleanField(
                default=True,
                help_text="Enable real-time teacher scoring of team submissions",
            ),
        ),
        migrations.AddField(
            model_name="designthinkinggame",
            name="phase_transition_delay",
            field=models.IntegerField(
                default=3,
                help_text="Seconds to wait before auto-advancing to next phase",
            ),
        ),
        migrations.AddField(
            model_name="designthinkinggame",
            name="scoring_system",
            field=models.CharField(
                choices=[
                    ("abc", "A/B/C Letter Grades"),
                    ("numeric", "1-10 Numeric Scale"),
                    ("stars", "1-5 Star Rating"),
                ],
                default="abc",
                help_text="Scoring system for teacher dashboard",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="PhaseCompletionTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_required_inputs",
                    models.PositiveIntegerField(
                        help_text="Total inputs required for this team to complete this phase"
                    ),
                ),
                (
                    "completed_inputs",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of inputs completed by team members",
                    ),
                ),
                (
                    "completion_percentage",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage of required inputs completed (0.0-100.0)",
                    ),
                ),
                (
                    "is_ready_to_advance",
                    models.BooleanField(
                        default=False,
                        help_text="Team has met completion threshold for auto-progression",
                    ),
                ),
                ("phase_completed_at", models.DateTimeField(blank=True, null=True)),
                ("auto_advanced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "completion_broadcasted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether completion status was broadcast via WebSocket",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="group_learning.designmission",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completion_tracking",
                        to="group_learning.designthinkingsession",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completion_status",
                        to="group_learning.designteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phase Completion Tracker",
                "verbose_name_plural": "Phase Completion Trackers",
                "ordering": ["-phase_completed_at"],
                "unique_together": {("session", "team", "mission")},
            },
        ),
        migrations.CreateModel(
            name="SimplifiedPhaseInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_name",
                    models.CharField(
                        help_text="Name of individual student (for individual completion tracking)",
                        max_length=100,
                    ),
                ),
                (
                    "student_session_id",
                    models.CharField(
                        help_text="Anonymous session ID for student", max_length=100
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("radio", "Radio Button Selection"),
                            ("dropdown", "Dropdown Selection"),
                            ("checkbox", "Checkbox Selection"),
                            ("text_short", "Short Text Input (50 chars)"),
                            ("text_medium", "Medium Text Input (200 chars)"),
                            ("rating", "Star Rating (1-5)"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "input_label",
                    models.CharField(
                        help_text="Question/prompt for this input", max_length=200
                    ),
                ),
                (
                    "selected_value",
                    models.CharField(
                        help_text="Student's selected/entered value", max_length=500
                    ),
                ),
                (
                    "input_order",
                    models.PositiveIntegerField(
                        default=1, help_text="Order of this input within the phase"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "time_to_complete_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Time taken to complete this specific input",
                    ),
                ),
                (
                    "teacher_score",
                    models.CharField(
                        blank=True,
                        help_text="Teacher's score for this input (A/B/C or 1-10 or 1-5 stars)",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("scored_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_inputs",
                        to="group_learning.designmission",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_inputs",
                        to="group_learning.designthinkingsession",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phase_inputs",
                        to="group_learning.designteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simplified Phase Input",
                "verbose_name_plural": "Simplified Phase Inputs",
                "ordering": ["-submitted_at"],
                "unique_together": {
                    ("team", "mission", "student_session_id", "input_order")
                },
            },
        ),
    ]
