# Generated by Django 5.2.5 on 2025-10-31 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_learning", "0017_remove_designmission_max_submissions_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phasecompletiontracker",
            options={
                "ordering": ["-phase_completed_at", "-updated_at"],
                "verbose_name": "Phase Completion Tracker",
                "verbose_name_plural": "Phase Completion Trackers",
            },
        ),
        migrations.AddField(
            model_name="designthinkinggame",
            name="max_teams_per_session",
            field=models.IntegerField(
                default=10,
                help_text="Maximum number of teams allowed per session",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
        migrations.AddField(
            model_name="designthinkinggame",
            name="session_timeout_minutes",
            field=models.IntegerField(
                default=120,
                help_text="Session timeout in minutes (default 2 hours)",
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(480),
                ],
            ),
        ),
        migrations.AddField(
            model_name="phasecompletiontracker",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="phasecompletiontracker",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="phasecompletiontracker",
            name="last_broadcast_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="phasecompletiontracker",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="simplifiedphaseinput",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="simplifiedphaseinput",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="simplifiedphaseinput",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="designthinkinggame",
            name="auto_advance_enabled",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Enable automatic phase progression when teams complete inputs",
            ),
        ),
        migrations.AlterField(
            model_name="designthinkinggame",
            name="completion_threshold_percentage",
            field=models.IntegerField(
                default=100,
                help_text="Percentage of team members required to complete phase (50-100%)",
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="designthinkinggame",
            name="phase_transition_delay",
            field=models.IntegerField(
                default=3,
                help_text="Seconds to wait before auto-advancing to next phase",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="phasecompletiontracker",
            name="completed_inputs",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of inputs completed by team members",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="phasecompletiontracker",
            name="completion_percentage",
            field=models.FloatField(
                default=0.0,
                help_text="Percentage of required inputs completed (0.0-100.0)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="phasecompletiontracker",
            name="is_ready_to_advance",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Team has met completion threshold for auto-progression",
            ),
        ),
        migrations.AlterField(
            model_name="phasecompletiontracker",
            name="phase_completed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="phasecompletiontracker",
            name="total_required_inputs",
            field=models.PositiveIntegerField(
                help_text="Total inputs required for this team to complete this phase",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedphaseinput",
            name="input_order",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Order of this input within the phase",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedphaseinput",
            name="scored_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="simplifiedphaseinput",
            name="student_session_id",
            field=models.CharField(
                db_index=True,
                help_text="Anonymous session ID for student",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedphaseinput",
            name="submitted_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="simplifiedphaseinput",
            name="teacher_score",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A - Excellent"),
                    ("B", "B - Good"),
                    ("C", "C - Needs Improvement"),
                    ("1", "1 Star"),
                    ("2", "2 Stars"),
                    ("3", "3 Stars"),
                    ("4", "4 Stars"),
                    ("5", "5 Stars"),
                    ("6", "6 Points"),
                    ("7", "7 Points"),
                    ("8", "8 Points"),
                    ("9", "9 Points"),
                    ("10", "10 Points"),
                ],
                help_text="Teacher's score for this input",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="simplifiedphaseinput",
            name="time_to_complete_seconds",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Time taken to complete this specific input",
                validators=[django.core.validators.MaxValueValidator(3600)],
            ),
        ),
        migrations.AddIndex(
            model_name="phasecompletiontracker",
            index=models.Index(
                fields=["session", "mission", "is_ready_to_advance"],
                name="group_learn_session_c65192_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="phasecompletiontracker",
            index=models.Index(
                fields=["team", "mission", "phase_completed_at"],
                name="group_learn_team_id_7df7f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="phasecompletiontracker",
            index=models.Index(
                fields=["session", "is_ready_to_advance", "updated_at"],
                name="group_learn_session_4281bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="simplifiedphaseinput",
            index=models.Index(
                fields=["team", "mission", "submitted_at"],
                name="group_learn_team_id_4d994c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="simplifiedphaseinput",
            index=models.Index(
                fields=["session", "submitted_at"],
                name="group_learn_session_61260a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="simplifiedphaseinput",
            index=models.Index(
                fields=["student_session_id", "submitted_at"],
                name="group_learn_student_466c9a_idx",
            ),
        ),
    ]
