# Generated by Django 5.2.5 on 2025-11-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_learning", "0018_alter_phasecompletiontracker_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="designteam",
            name="feedback_given_at",
            field=models.DateTimeField(
                blank=True, help_text="When teacher provided feedback", null=True
            ),
        ),
        migrations.AddField(
            model_name="designteam",
            name="teacher_feedback",
            field=models.TextField(
                blank=True,
                help_text="Teacher's feedback for this team's work",
                null=True,
            ),
        ),
    ]
