# Generated by Django 5.2.5 on 2025-11-01 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_learning", "0019_designteam_feedback_given_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamPhaseRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1 Star - Needs Significant Improvement"),
                            (2, "2 Stars - Below Expectations"),
                            (3, "3 Stars - Meets Expectations"),
                            (4, "4 Stars - Above Expectations"),
                            (5, "5 Stars - Exceptional Work"),
                        ]
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, help_text="Detailed feedback for the team"
                    ),
                ),
                (
                    "quick_notes",
                    models.CharField(
                        blank=True, help_text="Quick teacher notes", max_length=200
                    ),
                ),
                (
                    "submission_data",
                    models.JSONField(
                        default=dict, help_text="Snapshot of team submission when rated"
                    ),
                ),
                (
                    "submission_summary",
                    models.CharField(
                        blank=True, help_text="Auto-generated summary", max_length=500
                    ),
                ),
                ("rated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_final",
                    models.BooleanField(
                        default=False, help_text="Final rating (prevents changes)"
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_ratings",
                        to="group_learning.designmission",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="group_learning.designthinkingsession",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phase_ratings",
                        to="group_learning.designteam",
                    ),
                ),
            ],
            options={
                "ordering": ["-rated_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "mission"],
                        name="group_learn_session_d75dab_idx",
                    ),
                    models.Index(
                        fields=["team", "rating"], name="group_learn_team_id_da651c_idx"
                    ),
                ],
                "unique_together": {("team", "mission")},
            },
        ),
    ]
