# Generated by Django 5.2.5 on 2025-11-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_learning", "0020_teamphaserating"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="grade_level",
            field=models.CharField(
                blank=True,
                help_text="Grade level or class (e.g., '6th Grade', '7-8', 'High School')",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="school_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the school or educational institution",
                max_length=200,
            ),
        ),
    ]
