# Generated by Django 5.2.5 on 2025-11-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_learning", "0021_add_school_info_and_team_validation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designthinkinggame",
            name="scoring_system",
            field=models.CharField(
                choices=[
                    ("abc", "A/B/C Letter Grades"),
                    ("numeric", "1-10 Numeric Scale"),
                    ("stars", "1-5 Star Rating"),
                ],
                default="numeric",
                help_text="Scoring system for teacher dashboard",
                max_length=10,
            ),
        ),
    ]
