# Generated by Django 5.2.5 on 2025-11-06 00:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_learning", "0022_alter_designthinkinggame_scoring_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealtimeFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("submission_review", "Submission Review"),
                            ("teacher_message", "Teacher Message"),
                            ("ai_suggestion", "AI Suggestion"),
                            ("score_update", "Score Update"),
                            ("general_comment", "General Comment"),
                        ],
                        default="teacher_message",
                        max_length=20,
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[
                            ("teacher", "Teacher"),
                            ("ai", "AI Assistant"),
                            ("system", "System"),
                        ],
                        default="teacher",
                        max_length=10,
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(
                        default="Teacher",
                        help_text="Display name for sender",
                        max_length=100,
                    ),
                ),
                ("message", models.TextField(help_text="Feedback message content")),
                (
                    "score",
                    models.IntegerField(
                        blank=True,
                        help_text="Numerical score (1-10 scale)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_read", models.BooleanField(default=False)),
                ("is_urgent", models.BooleanField(default=False)),
                ("websocket_sent", models.BooleanField(default=False)),
                ("websocket_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realtime_feedback",
                        to="group_learning.designthinkingsession",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related submission (if feedback is about specific submission)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_messages",
                        to="group_learning.simplifiedphaseinput",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_feedback",
                        to="group_learning.designteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Realtime Feedback",
                "verbose_name_plural": "Realtime Feedback",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "team", "-created_at"],
                        name="group_learn_session_e81bc1_idx",
                    ),
                    models.Index(
                        fields=["team", "is_read", "-created_at"],
                        name="group_learn_team_id_879bd2_idx",
                    ),
                    models.Index(
                        fields=["submission", "-created_at"],
                        name="group_learn_submiss_12c7a9_idx",
                    ),
                    models.Index(
                        fields=["websocket_sent", "-created_at"],
                        name="group_learn_websock_f9028c_idx",
                    ),
                ],
            },
        ),
    ]
