# Generated by Django 5.2.5 on 2025-11-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_learning", "0023_add_realtime_feedback"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="designteam",
            constraint=models.UniqueConstraint(
                fields=("session",), name="unique_team_per_session"
            ),
        ),
    ]
