# Generated by Django 5.2.5 on 2025-11-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_learning", "0024_designteam_unique_team_per_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamsubmission",
            name="scored_at",
            field=models.DateTimeField(
                blank=True, help_text="When teacher scored this submission", null=True
            ),
        ),
        migrations.AddField(
            model_name="teamsubmission",
            name="teacher_feedback",
            field=models.TextField(blank=True, help_text="Optional teacher feedback"),
        ),
        migrations.AddField(
            model_name="teamsubmission",
            name="teacher_score",
            field=models.PositiveIntegerField(
                blank=True, help_text="Teacher score from 1-10", null=True
            ),
        ),
    ]
