# Generated by Django 5.2.5 on 2025-11-07 12:00

from django.db import migrations, models
import logging

logger = logging.getLogger(__name__)

def remove_duplicate_teams(apps, schema_editor):
    """Remove duplicate teams, keeping only the first one for each session"""
    DesignTeam = apps.get_model('group_learning', 'DesignTeam')
    DesignThinkingSession = apps.get_model('group_learning', 'DesignThinkingSession')

    deleted_count = 0
    sessions_processed = 0

    # Get all sessions that have multiple teams
    for session in DesignThinkingSession.objects.all():
        sessions_processed += 1
        teams = DesignTeam.objects.filter(session=session).order_by('id')
        if teams.count() > 1:
            # Keep the first team, delete the rest
            teams_to_delete = teams[1:]
            team_ids_deleted = [team.id for team in teams_to_delete]

            # Also handle related objects that reference these teams
            TeamSubmission = apps.get_model('group_learning', 'TeamSubmission')
            TeamProgress = apps.get_model('group_learning', 'TeamProgress')

            for team in teams_to_delete:
                # Move submissions to the first team (if any)
                TeamSubmission.objects.filter(team=team).update(team=teams.first())
                TeamProgress.objects.filter(team=team).update(team=teams.first())

            teams_to_delete.delete()
            deleted_count += len(team_ids_deleted)
            logger.info(f"Session {session.session_code}: Kept team {teams.first().id}, deleted teams {team_ids_deleted}")

    logger.info(f"Processed {sessions_processed} sessions, deleted {deleted_count} duplicate teams")

def remove_constraint_if_exists(apps, schema_editor):
    """Safely remove the unique constraint if it exists"""
    from django.db import connection

    # Use database-agnostic approach - try to remove constraint, ignore if doesn't exist
    try:
        with connection.cursor() as cursor:
            db_table = 'group_learning_designteam'
            constraint_name = 'unique_team_per_session'

            # For PostgreSQL
            if connection.vendor == 'postgresql':
                cursor.execute(f'ALTER TABLE {db_table} DROP CONSTRAINT IF EXISTS {constraint_name}')
                logger.info(f"Removed constraint {constraint_name} (PostgreSQL)")
            # For MySQL
            elif connection.vendor == 'mysql':
                cursor.execute(f'ALTER TABLE {db_table} DROP INDEX IF EXISTS {constraint_name}')
                logger.info(f"Removed constraint {constraint_name} (MySQL)")
            # For SQLite - constraints can't be dropped individually in SQLite
            elif connection.vendor == 'sqlite':
                logger.info("SQLite detected - constraint removal not needed")
    except Exception as e:
        # If constraint doesn't exist or any other error, just log and continue
        logger.warning(f"Could not remove constraint (this is okay if it doesn't exist): {e}")

def reverse_remove_duplicate_teams(apps, schema_editor):
    # This is irreversible
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('group_learning', '0025_add_simple_teacher_scoring'),
    ]

    operations = [
        # Step 1: Remove the unique constraint if it exists (from migration 0024)
        # This allows us to clean up duplicates without constraint violations
        migrations.RunPython(remove_constraint_if_exists, migrations.RunPython.noop),
        # Step 2: Clean up duplicate teams
        migrations.RunPython(remove_duplicate_teams, reverse_remove_duplicate_teams),
        # Step 3: Re-add the unique constraint after cleanup
        migrations.AddConstraint(
            model_name='designteam',
            constraint=models.UniqueConstraint(
                fields=['session'],
                name='unique_team_per_session'
            ),
        ),
    ]