# Generated by Django 5.2.5 on 2025-11-07 12:00

from django.db import migrations

def remove_duplicate_teams(apps, schema_editor):
    """Remove duplicate teams, keeping only the first one for each session"""
    DesignTeam = apps.get_model('group_learning', 'DesignTeam')
    DesignThinkingSession = apps.get_model('group_learning', 'DesignThinkingSession')
    
    # Get all sessions that have multiple teams
    for session in DesignThinkingSession.objects.all():
        teams = DesignTeam.objects.filter(session=session).order_by('id')
        if teams.count() > 1:
            # Keep the first team, delete the rest
            teams_to_delete = teams[1:]
            team_ids_deleted = [team.id for team in teams_to_delete]
            teams_to_delete.delete()
            print(f"Session {session.session_code}: Kept team {teams.first().id}, deleted teams {team_ids_deleted}")

def reverse_remove_duplicate_teams(apps, schema_editor):
    # This is irreversible
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('group_learning', '0025_add_simple_teacher_scoring'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_teams, reverse_remove_duplicate_teams),
    ]