# Generated by Django 5.2.5 on 2025-11-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_learning", "0026_remove_duplicate_teams"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="designteam",
            name="unique_team_per_session",
        ),
        migrations.AddConstraint(
            model_name="designteam",
            constraint=models.UniqueConstraint(
                fields=("session", "team_name"), name="unique_team_name_per_session"
            ),
        ),
    ]
