# Generated by Django 5.2.5 on 2025-11-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("group_learning", "0027_fix_design_team_unique_constraint"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="simplifiedphaseinput",
            unique_together={("team", "mission", "input_order")},
        ),
    ]
