# Generated by Django 5.2.5 on 2025-11-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_learning", "0028_remove_student_session_id_from_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="designteam",
            name="is_logged_in",
            field=models.BooleanField(
                default=False, help_text="Team current login status (future feature)"
            ),
        ),
        migrations.AddField(
            model_name="designteam",
            name="last_login_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last team login timestamp (future feature)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="designteam",
            name="team_password",
            field=models.CharField(
                blank=True,
                help_text="Team password for persistent login (future feature)",
                max_length=128,
                null=True,
            ),
        ),
    ]
