# Generated by Django 5.2.5 on 2025-11-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_learning", "0029_add_team_authentication_fields"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="simplifiedphaseinput",
            name="group_learn_team_id_4d994c_idx",
        ),
        migrations.RemoveIndex(
            model_name="simplifiedphaseinput",
            name="group_learn_session_61260a_idx",
        ),
        migrations.AlterUniqueTogether(
            name="simplifiedphaseinput",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="simplifiedphaseinput",
            name="phase_type",
            field=models.CharField(
                choices=[
                    ("intro", "Introduction"),
                    ("empathy", "Empathy - Understanding Problems"),
                    ("define", "Define - Problem Statement"),
                    ("ideate", "Ideate - Generating Solutions"),
                    ("prototype", "Prototype - Building Solutions"),
                    ("testing", "Testing - Getting Feedback"),
                ],
                db_index=True,
                default="empathy",
                help_text="Which design thinking phase this submission belongs to",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="simplifiedphaseinput",
            unique_together={("team", "session", "phase_type", "input_order")},
        ),
        migrations.AddIndex(
            model_name="simplifiedphaseinput",
            index=models.Index(
                fields=["team", "session", "phase_type"],
                name="group_learn_team_id_63ff8b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="simplifiedphaseinput",
            index=models.Index(
                fields=["session", "phase_type", "submitted_at"],
                name="group_learn_session_84cbf3_idx",
            ),
        ),
    ]
