# Generated by Django 5.2.5 on 2025-09-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robotic_buddy", "0002_alter_gameactivity_max_examples_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingexample",
            name="is_training_example",
            field=models.BooleanField(
                default=True,
                help_text="True for training phase, False for testing phase",
            ),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="testing_started_at",
            field=models.DateTimeField(
                blank=True, help_text="When testing phase started", null=True
            ),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="training_completed_at",
            field=models.DateTimeField(
                blank=True, help_text="When training phase completed", null=True
            ),
        ),
        migrations.AlterField(
            model_name="gameactivity",
            name="min_examples_needed",
            field=models.IntegerField(
                default=16, help_text="Minimum examples needed to 'train' buddy"
            ),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("training", "Training Phase"),
                    ("testing", "Testing Phase"),
                    ("completed", "Completed"),
                    ("abandoned", "Abandoned"),
                ],
                default="training",
                max_length=20,
            ),
        ),
    ]
