# Generated by Django 5.2.5 on 2025-09-15 18:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "action_type",
                    models.CharField(
                        help_text="Type of action (answer, move, vote, etc.)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField(help_text="Action-specific data")),
                ("points_earned", models.IntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["action_type", "created_at"],
                        name="games_gamea_action__604b33_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="games_gamea_created_483ec7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GameMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_name", models.CharField(max_length=100)),
                ("metric_value", models.FloatField()),
                ("metric_data", models.JSONField(default=dict)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["metric_name", "recorded_at"],
                        name="games_gamem_metric__f46a12_idx",
                    )
                ],
            },
        ),
    ]
